// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfcosbjzegntzonvmvsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmY29zYmp6ZWdudHpvbnZtdnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MTY5MjAsImV4cCI6MjA3OTA5MjkyMH0.nvsxfhFsDZXCCLtQyd7v8lew_MKgxufjKTf26xGgJtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});